import streamlit as st
import pandas as pd
import time
import altair as alt

# Page Config
st.set_page_config(
    page_title="Smart Traffic AI Monitor",
    page_icon="🚦",
    layout="wide"
)

# Title and Layout
st.title("🚦 Intelligent Traffic System Dashboard")
st.markdown("Real-time monitoring of Reinforcement Learning agents controlling city traffic.")

# Placeholders for live data
col1, col2, col3 = st.columns(3)
with col1:
    metric_cars = st.empty()
with col2:
    metric_queue = st.empty()
with col3:
    metric_reward = st.empty()

# Charts
st.subheader("📊 Live Traffic Analytics")
chart_col1, chart_col2 = st.columns(2)
with chart_col1:
    st.markdown("**🚗 Queue Length Over Time**")
    queue_chart = st.empty()
with chart_col2:
    st.markdown("**👁️ Computer Vision Detection**")
    vision_chart = st.empty()

def load_data():
    try:
        # Read the CSV generated by run_simulation.py
        df = pd.read_csv("simulation_data.csv")
        return df
    except FileNotFoundError:
        return pd.DataFrame()

# Live Update Loop
st.markdown("---")
status_text = st.empty()

while True:
    df = load_data()
    
    if not df.empty:
        # Get latest row
        latest = df.iloc[-1]
        
        # Update Top Metrics
        metric_cars.metric(label="Total Vehicles", value=int(latest['cars']))
        metric_queue.metric(label="Total Queue Length", value=int(latest['queue']), delta_color="inverse")
        metric_reward.metric(label="AI Reward", value=f"{latest['reward']:.2f}")
        
        # 1. Line Chart: Queue & Cars
        chart_data = df[['step', 'queue', 'cars']].melt('step')
        c = alt.Chart(chart_data).mark_line().encode(
            x='step', 
            y='value', 
            color='variable',
            tooltip=['step', 'value', 'variable']
        ).interactive()
        queue_chart.altair_chart(c, use_container_width=True)
        
        # 2. Bar Chart: Vision Data (Last Step)
        vis_data = pd.DataFrame({
            'Type': ['Pedestrians', 'Cars', 'Ambulances', 'Trucks'],
            'Count': [latest['peds'], latest['cars'], latest['ambulance'], latest['trucks']]
        })
        
        # Alert if Ambulance detected
        if latest['ambulance'] > 0:
            status_text.error(f"🚨 EMERGENCY DETECTED AT STEP {latest['step']}! PRIORITY MODE ACTIVE.")
        else:
            status_text.success("✅ System Status: Normal Operation")

        b = alt.Chart(vis_data).mark_bar().encode(
            x='Type',
            y='Count',
            color=alt.condition(
                alt.datum.Type == 'Ambulances',
                alt.value('red'),  # The positive color
                alt.value('steelblue')  # The negative color
            )
        )
        vision_chart.altair_chart(b, use_container_width=True)

    time.sleep(1) # Refresh every second